const { SlashCommandBuilder, PermissionFlagsBits, ChannelType, PermissionsBitField } = require('discord.js');
const crypto = require('node:crypto');
const { createEmbed } = require('../utils');
const { COLOR_SUCCESS, COLOR_PRIMARY, COLOR_DANGER, COLOR_INFO, E } = require('../config');
const { getEmbed } = require('../embed_config');
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function backupId(){return crypto.randomUUID().slice(0,8);}
async function backupsCol(bot){await bot.db.connect(); return bot.db.db.collection('backups');}
async function collectBackupData(guild){
  const roles=[...guild.roles.cache.values()].sort((a,b)=>b.position-a.position).filter(r=>r.id!==guild.id&&!r.managed).map(r=>({name:r.name,color:r.color,permissions:r.permissions.bitfield.toString(),hoist:r.hoist,mentionable:r.mentionable,position:r.position,role_id:r.id}));
  const categories=[...guild.channels.cache.values()].filter(c=>c.type===ChannelType.GuildCategory).map(cat=>({name:cat.name,position:cat.position,overwrites:{},id:cat.id}));
  const channels=[...guild.channels.cache.values()].filter(ch=>ch.type!==ChannelType.GuildCategory).map(ch=>{const d={name:ch.name,type:String(ch.type),position:ch.position,category_id:ch.parentId}; if('topic'in ch)d.topic=ch.topic; if('rateLimitPerUser'in ch)d.slowmode_delay=ch.rateLimitPerUser; if('nsfw'in ch)d.nsfw=ch.nsfw; if('bitrate'in ch)d.bitrate=ch.bitrate; if('userLimit'in ch)d.user_limit=ch.userLimit; return d;});
  return {guild_id:guild.id,guild_name:guild.name,roles,categories,channels,icon_url:guild.iconURL?.()||null,created_at:new Date().toISOString()};
}
async function backupDbSave(bot,backupData,createdBy,label=null,passwordHash=null){const id=backupId();const doc={backup_id:id,guild_id:backupData.guild_id,guild_id_str:String(backupData.guild_id),guild_name:backupData.guild_name,data:backupData,created_by:createdBy,created_at:new Date(),label,password_hash:passwordHash};await (await backupsCol(bot)).insertOne(doc);return id;}
async function backupDbGet(bot,guildId,id){const variants=[String(guildId),Number(guildId)];return (await backupsCol(bot)).findOne({backup_id:id,$or:[{guild_id:{$in:variants}},{guild_id_str:String(guildId)},{'data.guild_id':{$in:variants}}]});}
async function restoreFromBackup(guild,backup){const report={roles_created:0,channels_created:0,errors:[]};const roleMap=new Map();for(const rd of [...(backup.roles||[])].reverse()){try{let existing=guild.roles.cache.get(String(rd.role_id));if(existing){roleMap.set(rd.role_id,existing);continue;}const role=await guild.roles.create({name:rd.name,color:rd.color||0,permissions:BigInt(rd.permissions||0),hoist:!!rd.hoist,mentionable:!!rd.mentionable,reason:'Backup-Wiederherstellung'});roleMap.set(rd.role_id,role);report.roles_created++;await sleep(500);}catch(e){report.errors.push(`Rolle ${rd.name}: ${e.message}`);}}
const catMap=new Map();for(const cd of backup.categories||[]){try{let existing=guild.channels.cache.find(c=>c.type===ChannelType.GuildCategory&&c.name===cd.name);if(existing){catMap.set(cd.id,existing);continue;}const cat=await guild.channels.create({name:cd.name,type:ChannelType.GuildCategory,reason:'Backup-Wiederherstellung'});catMap.set(cd.id,cat);await sleep(300);}catch(e){report.errors.push(`Kategorie ${cd.name}: ${e.message}`);}}
for(const chd of backup.channels||[]){try{if(guild.channels.cache.find(c=>c.name===chd.name))continue;const parent=catMap.get(chd.category_id);if(String(chd.type).includes('2')||String(chd.type).includes('voice'))await guild.channels.create({name:chd.name,type:ChannelType.GuildVoice,parent:parent?.id,bitrate:chd.bitrate,userLimit:chd.user_limit,reason:'Backup'});else await guild.channels.create({name:chd.name,type:ChannelType.GuildText,parent:parent?.id,topic:chd.topic||undefined,rateLimitPerUser:chd.slowmode_delay||0,nsfw:!!chd.nsfw,reason:'Backup'});report.channels_created++;await sleep(300);}catch(e){report.errors.push(`Kanal ${chd.name}: ${e.message}`);}}return report;}
const commands=[
{data:new SlashCommandBuilder().setName('backup_create').setDescription('Erstellt ein Server-Backup').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('label').setDescription('Optionales Label').setRequired(false)),async execute(bot,i){await i.deferReply();try{const data=await collectBackupData(i.guild);const id=await backupDbSave(bot,data,i.user.id,i.options.getString('label'));await i.followUp({embeds:[createEmbed(`${E.OK} Backup erstellt`,`Backup-ID: \`${id}\`\nRollen: **${data.roles.length}**\nKanäle: **${data.channels.length}**`,COLOR_SUCCESS)]});}catch(e){await i.followUp({embeds:[createEmbed(`${E.FAIL}`,`Fehler: ${e.message}`,COLOR_DANGER)]});}}},
{data:new SlashCommandBuilder().setName('backup_list').setDescription('Zeigt alle Backups').setDefaultMemberPermissions(PermissionFlagsBits.Administrator),async execute(bot,i){const docs=await (await backupsCol(bot)).find({$or:[{guild_id:i.guild.id},{guild_id:String(i.guild.id)},{guild_id_str:String(i.guild.id)}]}).sort({created_at:-1}).limit(10).toArray();if(!docs.length)return i.reply({embeds:[createEmbed(`${E.OK}`,'Keine Backups vorhanden.',COLOR_INFO)],ephemeral:true});const lines=docs.map(d=>`\`${d.backup_id}\` – ${d.label||'Ohne Label'} – ${d.created_at?new Date(d.created_at).toLocaleString('de-DE'):'?'}`);await i.reply({embeds:[createEmbed(`${E.SAVE} Backups`,lines.join('\n'),COLOR_PRIMARY)],ephemeral:true});}},
{data:new SlashCommandBuilder().setName('backup_restore').setDescription('Stellt ein Backup wieder her').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('backup_id').setDescription('Backup-ID').setRequired(true)),async execute(bot,i){await i.deferReply();const id=i.options.getString('backup_id',true);const doc=await backupDbGet(bot,i.guild.id,id);if(!doc)return i.followUp({embeds:[createEmbed(`${E.FAIL}`,'Backup nicht gefunden.',COLOR_DANGER)]});const report=await restoreFromBackup(i.guild,doc.data||{});await i.followUp({embeds:[createEmbed(`${E.OK} Backup wiederhergestellt`,`Rollen erstellt: **${report.roles_created}**\nKanäle erstellt: **${report.channels_created}**\nFehler: **${report.errors.length}**`,report.errors.length?COLOR_WARNING:COLOR_SUCCESS,[['Fehler',report.errors.slice(0,10).join('\n')||'Keine',false]])]});}},
{data:new SlashCommandBuilder().setName('backup_delete').setDescription('Löscht ein Backup').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('backup_id').setDescription('Backup-ID').setRequired(true)),async execute(bot,i){const id=i.options.getString('backup_id',true);const res=await (await backupsCol(bot)).deleteOne({backup_id:id,$or:[{guild_id:i.guild.id},{guild_id:String(i.guild.id)},{guild_id_str:String(i.guild.id)}]});if(res.deletedCount)await i.reply({embeds:[createEmbed(`${E.OK}`,'Backup gelöscht.',COLOR_SUCCESS)],ephemeral:true});else await i.reply({embeds:[createEmbed(`${E.FAIL}`,'Backup nicht gefunden.',COLOR_DANGER)],ephemeral:true});}},
];
module.exports={commands,collectBackupData,restoreFromBackup};
