const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');
const { createEmbed, reply } = require('../utils');
const { COLOR_PRIMARY, COLOR_SUCCESS, COLOR_WARNING } = require('../config');
function riskScore(member){let score=0;const age=Date.now()-member.user.createdTimestamp;if(age<7*864e5)score+=35;if(!member.user.avatar)score+=10;if(member.roles.cache.size<=1)score+=10;return Math.min(100,score);}
const commands=[
{data:new SlashCommandBuilder().setName('theme').setDescription('[BETA] Setze das Theme für diesen Server').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('theme').setDescription('dark/light/midnight/sunset/forest/neon/ocean/lavender').setRequired(true)),async execute(bot,i){const theme=i.options.getString('theme',true);await bot.db.setServerTheme(i.guild.id,theme);return reply(i,{embeds:[createEmbed('🧪 Theme gespeichert',`Theme: **${theme}**`,COLOR_SUCCESS)]},true);}},
{data:new SlashCommandBuilder().setName('risk').setDescription('[BETA] Zeigt das Risiko-Profil eines Users').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)),async execute(bot,i){const u=i.options.getUser('member',true);const m=await i.guild.members.fetch(u.id);const score=riskScore(m);return reply(i,{embeds:[createEmbed('🧪 Risk-Profil',`${u}\nRisk-Score: **${score}/100**`,score>=50?COLOR_WARNING:COLOR_PRIMARY)]},true);}},
{data:new SlashCommandBuilder().setName('appeal').setDescription('[BETA] Stelle einen Entbannungs-Antrag').addStringOption(o=>o.setName('reason').setDescription('Grund').setRequired(true)),async execute(bot,i){await bot.db.appeals.insertOne({guild_id:Number(i.guild.id),user_id:i.user.id,reason:i.options.getString('reason',true),status:'pending',created_at:new Date()});return reply(i,{embeds:[createEmbed('🧪 Appeal erstellt','Dein Entbannungs-Antrag wurde gespeichert.',COLOR_SUCCESS)]},true);}},
{data:new SlashCommandBuilder().setName('apply').setDescription('[BETA] Bewirb dich als Staff-Mitglied').addStringOption(o=>o.setName('question').setDescription('Antwort/Bewerbung').setRequired(true)),async execute(bot,i){await bot.db.staff_applications.insertOne({guild_id:Number(i.guild.id),user_id:i.user.id,question:i.options.getString('question',true),status:'pending',created_at:new Date()});return reply(i,{embeds:[createEmbed('🧪 Bewerbung gespeichert','Deine Staff-Bewerbung wurde gespeichert.',COLOR_SUCCESS)]},true);}},
];
const events=[{name:'guildMemberUpdate',async execute(bot,before,after){const cfg=await bot.db.fetchConfig(after.guild.id);if(cfg.beta_features?.risk_alerts&&riskScore(after)>70)await bot.logAction(after.guild,'🧪 Risk Alert',`${after} hat einen hohen Risk-Score.`,COLOR_WARNING,{module:'moderation'});}}];
module.exports={commands,events};
