const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');
const { createEmbed, reply } = require('../utils');
const { COLOR_PRIMARY, COLOR_SUCCESS, COLOR_DANGER, COLOR_WARNING } = require('../config');
const events=[
{name:'guildMemberAdd',async execute(bot,member){const cfg=await bot.db.fetchConfig(member.guild.id);if(cfg.anti_raid?.enabled){const arr=bot.tracker.raidTracker.get(member.guild.id)||[];const now=Date.now();const windowSeconds=cfg.anti_raid.window||20;const threshold=cfg.anti_raid.join_threshold||cfg.anti_raid.joins||10;arr.push(now);while(arr.length&&now-arr[0]>windowSeconds*1000)arr.shift();bot.tracker.raidTracker.set(member.guild.id,arr);if(arr.length>=threshold){bot.tracker.lockdownActive.set(member.guild.id,true);await bot.logAction(member.guild,'🚨 Anti-Raid',`Raid erkannt: **${arr.length}** Joins im Zeitfenster.`,COLOR_DANGER,{module:'antiraid'});}}}},
{name:'webhookUpdate',async execute(bot,channel){await bot.logAction(channel.guild,'🔌 Webhook-Update',`Webhooks in ${channel} wurden geändert.`,COLOR_WARNING,{module:'webhooks'});}},
{name:'guildUpdate',async execute(bot,before,after){await bot.logAction(after,'💥 Server-Update',`Server **${before.name}** wurde geändert.`,COLOR_WARNING,{module:'antinuke'});}}, 
];
const commands=[
{data:new SlashCommandBuilder().setName('snapshot').setDescription('Vergleicht Server mit letztem Snapshot').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),async execute(bot,i){return reply(i,{embeds:[createEmbed('📸 Snapshot',`Rollen: **${i.guild.roles.cache.size}**\nChannels: **${i.guild.channels.cache.size}**\nMember: **${i.guild.memberCount}**`,COLOR_PRIMARY)]},true);}},
{data:new SlashCommandBuilder().setName('panic').setDescription('Panic-Button: Sofortiger Lockdown').setDefaultMemberPermissions(PermissionFlagsBits.Administrator),async execute(bot,i){bot.tracker.lockdownActive.set(i.guild.id,true);await bot.logAction(i.guild,'🚨 Panic Button',`${i.user} hat den Panic-Button ausgelöst.`,COLOR_DANGER,{module:'antinuke'});return reply(i,{embeds:[createEmbed('🚨 Panic aktiviert','Sofortiger Lockdown wurde markiert.',COLOR_DANGER)]},true);}},
{data:new SlashCommandBuilder().setName('nuke_whitelist').setDescription('Nuke-Whitelist verwalten').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('action').setDescription('add/remove/list').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('User').setRequired(false)).addRoleOption(o=>o.setName('role').setDescription('Rolle').setRequired(false)),async execute(bot,i){const wl=await bot.db.fetchWhitelist(i.guild.id);const action=i.options.getString('action',true);const user=i.options.getUser('user');const role=i.options.getRole('role');if(action==='add'&&user&&!wl.users.includes(user.id))wl.users.push(user.id);if(action==='add'&&role&&!wl.roles.includes(role.id))wl.roles.push(role.id);if(action==='remove'&&user)wl.users=wl.users.filter(x=>x!==user.id);if(action==='remove'&&role)wl.roles=wl.roles.filter(x=>x!==role.id);await bot.db.setWhitelist(i.guild.id,wl);return reply(i,{embeds:[createEmbed('🛡️ Nuke-Whitelist',`Users: ${wl.users.length}\nRoles: ${wl.roles.length}`,COLOR_SUCCESS)]},true);}},
{data:new SlashCommandBuilder().setName('emergency_contact').setDescription('Emergency-Contact hinzufügen').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('action').setDescription('add/remove/list').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('User').setRequired(false)),async execute(bot,i){const cfg=await bot.db.fetchConfig(i.guild.id);cfg.emergency_contacts=cfg.emergency_contacts||[];const action=i.options.getString('action',true);const user=i.options.getUser('user');if(action==='add'&&user&&!cfg.emergency_contacts.includes(user.id))cfg.emergency_contacts.push(user.id);if(action==='remove'&&user)cfg.emergency_contacts=cfg.emergency_contacts.filter(x=>x!==user.id);await bot.db.setConfig(i.guild.id,cfg);return reply(i,{embeds:[createEmbed('🚨 Emergency Contacts',`${cfg.emergency_contacts.length} Kontakte gespeichert.`,COLOR_SUCCESS)]},true);}},
{data:new SlashCommandBuilder().setName('bot_approve').setDescription('Genehmigt einen Bot (wenn Bot-Approval aktiv)').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('bot_id').setDescription('Bot ID').setRequired(true)),async execute(bot,i){const cfg=await bot.db.fetchConfig(i.guild.id);cfg.approved_bots=cfg.approved_bots||[];const id=i.options.getString('bot_id',true);if(!cfg.approved_bots.includes(id))cfg.approved_bots.push(id);await bot.db.setConfig(i.guild.id,cfg);return reply(i,{embeds:[createEmbed('✅ Bot approved',`Bot **${id}** wurde genehmigt.`,COLOR_SUCCESS)]},true);}},
];module.exports={commands,events};
