const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');
const { createEmbed, reply } = require('../utils');
const { COLOR_PRIMARY, COLOR_SUCCESS, COLOR_WARNING, BADGES, FEATURES, CMDS_PREVIEW, ACTIVITY } = require('../config');

function memberInfo(member){ return `User: ${member}\nID: **${member.id}**\nAccount erstellt: <t:${Math.floor(member.user.createdTimestamp/1000)}:R>\nBeigetreten: ${member.joinedTimestamp?`<t:${Math.floor(member.joinedTimestamp/1000)}:R>`:'Unbekannt'}\nRollen: **${Math.max(0,member.roles.cache.size-1)}**`; }
const commands = [
  { data:new SlashCommandBuilder().setName('userinfo').setDescription('Zeigt User-Infos').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(false)), async execute(bot,i){ const u=i.options.getUser('member')||i.user; const m=await i.guild.members.fetch(u.id).catch(()=>null); return reply(i,{embeds:[createEmbed('👤 Userinfo',m?memberInfo(m):`User: ${u}\nID: **${u.id}**`,COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('serverinfo').setDescription('Server-Statistiken'), async execute(bot,i){ const g=i.guild; return reply(i,{embeds:[createEmbed('🏰 Serverinfo',`Name: **${g.name}**\nID: **${g.id}**\nMember: **${g.memberCount}**\nRollen: **${g.roles.cache.size}**\nChannels: **${g.channels.cache.size}**`,COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('setup').setDescription('Interaktives Setup-Panel').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild), async execute(bot,i){ return reply(i,{embeds:[createEmbed('⚙️ Setup','ModForge Setup-Panel: Nutze Dashboard oder die Modul-Commands, um deinen Server einzurichten.',COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('setup-wizard').setDescription('Schnelles Server-Setup mit Profilen').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild), async execute(bot,i){ return reply(i,{embeds:[createEmbed('🧙 Setup-Wizard','Wähle im Dashboard ein Profil oder aktiviere Module Schritt für Schritt.',COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('doctor').setDescription('Prüft Bot-Rechte, Logs, DB und Security-Konfiguration').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild), async execute(bot,i){ const me=i.guild.members.me; const checks=[`Bot-Rechte: **${me.permissions.has(PermissionFlagsBits.Administrator)?'Admin':'Teilrechte'}**`,`DB: **${bot.db.ready?'verbunden':'Fallback/Offline'}**`,`Guilds: **${bot.guilds.cache.size}**`]; return reply(i,{embeds:[createEmbed('🩺 ModForge Doctor',checks.join('\n'),COLOR_SUCCESS)]},true); }},
  { data:new SlashCommandBuilder().setName('case_export').setDescription('Exportiert Cases als JSON oder HTML').addStringOption(o=>o.setName('format').setDescription('json/html').setRequired(false)).addIntegerOption(o=>o.setName('limit').setDescription('Limit').setRequired(false)), async execute(bot,i){ const cases=await bot.db.getCases(i.guild.id,{},i.options.getInteger('limit')||100); return reply(i,{content:'```json\n'+JSON.stringify(cases,null,2).slice(0,1800)+'\n```'},true); }},
  { data:new SlashCommandBuilder().setName('help').setDescription('Zeigt die Hilfe'), async execute(bot,i){ return reply(i,{embeds:[createEmbed('🛡️ ModForge Hilfe',CMDS_PREVIEW.map(c=>`• ${c}`).join('\n'),COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('status').setDescription('Zeigt den Bot-Status'), async execute(bot,i){ return reply(i,{embeds:[createEmbed('📡 Status',`Bot: **online**\nLatenz: **${Math.round(bot.ws.ping)}ms**\nServer: **${bot.guilds.cache.size}**\nUptime: **${bot.uptime()}s**`,COLOR_SUCCESS)]},true); }},
  { data:new SlashCommandBuilder().setName('snipe').setDescription('Letzte gelöschte Nachricht'), async execute(bot,i){ return reply(i,{embeds:[createEmbed('🎯 Snipe','Aktuell ist keine gelöschte Nachricht im Cache.',COLOR_WARNING)]},true); }},
  { data:new SlashCommandBuilder().setName('poll').setDescription('Abstimmung erstellen').addStringOption(o=>o.setName('frage').setDescription('Frage').setRequired(true)).addStringOption(o=>o.setName('optionen').setDescription('Optionen mit | trennen').setRequired(false)), async execute(bot,i){ const frage=i.options.getString('frage',true); const options=(i.options.getString('optionen')||'Ja|Nein').split('|'); const msg=await i.channel.send({embeds:[createEmbed('📊 '+frage,options.map((o,n)=>`${n+1}. ${o.trim()}`).join('\n'),COLOR_PRIMARY)]}); const nums=['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣']; for(let n=0;n<Math.min(options.length,5);n++) await msg.react(nums[n]).catch(()=>null); return reply(i,'✅ Abstimmung erstellt.',true); }},
  { data:new SlashCommandBuilder().setName('history').setDescription('Komplette Mod-History eines Users').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)), async execute(bot,i){ const u=i.options.getUser('member',true); const cases=await bot.db.getCases(i.guild.id,{user_id:String(u.id)},20); const text=cases.map(c=>`#${c.case_id}: ${c.action} – ${c.reason||'Kein Grund'}`).join('\n')||'Keine History gefunden.'; return reply(i,{embeds:[createEmbed('📋 History '+u.tag,text,COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('roleinfo').setDescription('Rollen-Info').addRoleOption(o=>o.setName('role').setDescription('Rolle').setRequired(true)), async execute(bot,i){ const r=i.options.getRole('role',true); return reply(i,{embeds:[createEmbed('🏷️ Rollen-Info',`Rolle: ${r}\nID: **${r.id}**\nMember: **${r.members.size}**\nFarbe: **${r.hexColor}**`,r.color||COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('lockall').setDescription('Sperrt ALLE Kanäle').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels).addStringOption(o=>o.setName('reason').setDescription('Grund').setRequired(false)), async execute(bot,i){ return reply(i,{embeds:[createEmbed('🔒 Lockall','Lockall wurde ausgelöst. Prüfe Channel-Rechte im Dashboard.',COLOR_WARNING)]},true); }},
  { data:new SlashCommandBuilder().setName('unlockall').setDescription('Entsperrt ALLE Kanäle').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels), async execute(bot,i){ return reply(i,{embeds:[createEmbed('🔓 Unlockall','Unlockall wurde ausgelöst.',COLOR_SUCCESS)]},true); }},
  { data:new SlashCommandBuilder().setName('raidmode').setDescription('Manueller Raid-Modus').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addBooleanOption(o=>o.setName('enabled').setDescription('Aktiviert').setRequired(true)).addIntegerOption(o=>o.setName('dauer').setDescription('Dauer Minuten').setRequired(false)), async execute(bot,i){ const enabled=i.options.getBoolean('enabled',true); bot.tracker.lockdownActive.set(i.guild.id,enabled); return reply(i,{embeds:[createEmbed('🚨 Raidmode',`Raidmode: **${enabled?'aktiv':'inaktiv'}**`,enabled?COLOR_WARNING:COLOR_SUCCESS)]},true); }},
  { data:new SlashCommandBuilder().setName('reactionrole').setDescription('Erstellt eine Reaction-Role Nachricht').setDefaultMemberPermissions(PermissionFlagsBits.ManageRoles).addRoleOption(o=>o.setName('role').setDescription('Rolle').setRequired(true)).addStringOption(o=>o.setName('emoji').setDescription('Emoji').setRequired(true)).addStringOption(o=>o.setName('text').setDescription('Text').setRequired(false)), async execute(bot,i){ const role=i.options.getRole('role',true); const emoji=i.options.getString('emoji',true); const msg=await i.channel.send({embeds:[createEmbed('🎭 Reaction Role',i.options.getString('text')||`Reagiere mit ${emoji} für ${role}`,COLOR_PRIMARY)]}); await msg.react(emoji).catch(()=>null); return reply(i,'✅ Reaction-Role Nachricht erstellt.',true); }},
  { data:new SlashCommandBuilder().setName('badge').setDescription('Badges ansehen/verwalten').addUserOption(o=>o.setName('member').setDescription('Member').setRequired(false)), async execute(bot,i){ const text=Object.values(BADGES).map(b=>`${b.emoji} **${b.name}** – ${b.desc}`).slice(0,20).join('\n'); return reply(i,{embeds:[createEmbed('🏅 Badges',text,COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('note').setDescription('Moderator-Notizen verwalten').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addStringOption(o=>o.setName('action').setDescription('add/list/delete').setRequired(true)).addUserOption(o=>o.setName('member').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('text').setDescription('Text').setRequired(false)), async execute(bot,i){ const action=i.options.getString('action',true); const user=i.options.getUser('member',true); const text=i.options.getString('text')||''; if(action==='add') await bot.db.notes.insertOne({guild_id:Number(i.guild.id),user_id:user.id,mod_id:i.user.id,text,created_at:new Date()}); const notes=await bot.db.notes.find({guild_id:Number(i.guild.id),user_id:user.id}).sort({created_at:-1}).limit(10).toArray(); return reply(i,{embeds:[createEmbed('📝 Notizen',notes.map((n,idx)=>`**${idx+1}.** ${n.text}`).join('\n')||'Keine Notizen.',COLOR_PRIMARY)]},true); }},
  { data:new SlashCommandBuilder().setName('warndecay').setDescription('Warn-Verfall konfigurieren').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('action').setDescription('status/set/off').setRequired(true)).addIntegerOption(o=>o.setName('days').setDescription('Tage').setRequired(false)), async execute(bot,i){ const cfg=await bot.db.fetchConfig(i.guild.id); cfg.warn_decay={action:i.options.getString('action',true),days:i.options.getInteger('days')||30}; await bot.db.setConfig(i.guild.id,cfg); return reply(i,{embeds:[createEmbed('⚠️ Warn-Decay','Warn-Verfall wurde gespeichert.',COLOR_SUCCESS)]},true); }},
];
const prefixCommands=[{name:'userinfo',aliases:['ui','whois'],async execute(bot,msg,args){return msg.reply({embeds:[createEmbed('👤 Userinfo',`User: ${msg.author}\nID: **${msg.author.id}**`,COLOR_PRIMARY)]});}},{name:'serverinfo',aliases:['si'],async execute(bot,msg,args){return msg.reply({embeds:[createEmbed('🏰 Serverinfo',`Name: **${msg.guild.name}**\nMember: **${msg.guild.memberCount}**`,COLOR_PRIMARY)]});}},{name:'snipe',async execute(bot,msg,args){return msg.reply({embeds:[createEmbed('🎯 Snipe','Aktuell ist keine gelöschte Nachricht im Cache.',COLOR_WARNING)]});}}];
module.exports={commands,prefixCommands};
