const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');
const { createEmbed, reply, embedPayload } = require('../utils');
const { COLOR_SUCCESS, COLOR_PRIMARY } = require('../config');

const commands = [
  { data: new SlashCommandBuilder().setName('setup_verify').setDescription('Richtet das Verifizierungssystem ein').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addChannelOption(o=>o.setName('channel').setDescription('Verify-Kanal').setRequired(true)).addStringOption(o=>o.setName('mode').setDescription('one_click/captcha').setRequired(false)), async execute(bot,i){ const cfg=await bot.db.fetchConfig(i.guild.id); cfg.verify_system=cfg.verify_system||{}; cfg.verify_system.enabled=true; cfg.verify_system.channel_id=i.options.getChannel('channel',true).id; cfg.verify_system.verify_channel=i.options.getChannel('channel',true).id; cfg.verify_system.mode=i.options.getString('mode')||'one_click'; await bot.db.setConfig(i.guild.id,cfg); return reply(i,{embeds:[createEmbed('✅ Verify eingerichtet','Verifizierungssystem wurde gespeichert.',COLOR_SUCCESS)]},true); } },
  { data: new SlashCommandBuilder().setName('verify_roles').setDescription('Verify-Rollen einstellen').setDefaultMemberPermissions(PermissionFlagsBits.ManageRoles).addRoleOption(o=>o.setName('add_role').setDescription('Rolle hinzufügen').setRequired(false)).addRoleOption(o=>o.setName('remove_role').setDescription('Rolle entfernen').setRequired(false)), async execute(bot,i){ const cfg=await bot.db.fetchConfig(i.guild.id); cfg.verify_system=cfg.verify_system||{}; const add=i.options.getRole('add_role'); const rem=i.options.getRole('remove_role'); if(add)cfg.verify_system.add_roles=[add.id]; if(rem)cfg.verify_system.remove_roles=[rem.id]; await bot.db.setConfig(i.guild.id,cfg); return reply(i,{embeds:[createEmbed('✅ Verify-Rollen','Verify-Rollen wurden gespeichert.',COLOR_SUCCESS)]},true); } },
  { data: new SlashCommandBuilder().setName('verify_quiz_add').setDescription('Quiz-Frage hinzufügen').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName('question').setDescription('Frage').setRequired(true)).addStringOption(o=>o.setName('answer').setDescription('Antwort').setRequired(true)), async execute(bot,i){ const cfg=await bot.db.fetchConfig(i.guild.id); cfg.verify_system=cfg.verify_system||{}; cfg.verify_system.quiz=cfg.verify_system.quiz||[]; cfg.verify_system.quiz.push({question:i.options.getString('question',true),answer:i.options.getString('answer',true)}); await bot.db.setConfig(i.guild.id,cfg); return reply(i,{embeds:[createEmbed('✅ Quiz-Frage','Quiz-Frage wurde hinzugefügt.',COLOR_SUCCESS)]},true); } },
  { data: new SlashCommandBuilder().setName('verify_timer').setDescription('Auto-Kick Timer für unverifizierte User').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addIntegerOption(o=>o.setName('minutes').setDescription('Minuten').setRequired(false)).addStringOption(o=>o.setName('action').setDescription('kick/none').setRequired(false)), async execute(bot,i){ const cfg=await bot.db.fetchConfig(i.guild.id); cfg.verify_system=cfg.verify_system||{}; cfg.verify_system.timer_minutes=i.options.getInteger('minutes')||10; cfg.verify_system.timer_action=i.options.getString('action')||'kick'; await bot.db.setConfig(i.guild.id,cfg); return reply(i,{embeds:[createEmbed('⏱️ Verify-Timer','Verify-Timer wurde gespeichert.',COLOR_SUCCESS)]},true); } },
  { data: new SlashCommandBuilder().setName('verify_stats').setDescription('Verifizierungs-Statistiken'), async execute(bot,i){ const full=await bot.db.fetchConfig(i.guild.id); const cfg=full.verify_system||{}; return reply(i,{embeds:[createEmbed('✅ Verify-Stats',`Aktiv: **${!!cfg.enabled}**\nModus: **${cfg.mode||'one_click'}**\nQuiz-Fragen: **${(cfg.quiz||[]).length}**`,COLOR_PRIMARY)]},true); } },
];

async function sendVerifyDm(bot, member, reason = 'Verifizierung erfolgreich!') {
  await member.send(embedPayload(createEmbed('✅ Verifizierung erfolgreich', `**Server:** ${member.guild.name}\n${reason}`, COLOR_SUCCESS, [], { author: member.client?.user, guild: member.guild }), { author: member.client?.user, guild: member.guild })).catch(() => null);
  await bot.db.data.insertOne({ type: 'verify_dm', guild_id: Number(member.guild.id), user_id: String(member.id), reason, created_at: new Date() }).catch(() => null);
}

const events = [
  { name:'interactionCreate', async execute(bot,i){ if(!i.isButton()||i.customId!=='modforge:verify')return; const full=await bot.db.fetchConfig(i.guild.id); const cfg=full.verify_system||{}; const add=cfg.add_roles||[]; const rem=cfg.remove_roles||[]; for(const id of add)await i.member.roles.add(id,'Verifizierung erfolgreich').catch(()=>null); for(const id of rem)await i.member.roles.remove(id,'Verifizierung erfolgreich').catch(()=>null); await sendVerifyDm(bot, i.member, 'Du wurdest über den Verify-Button verifiziert.'); await i.reply({embeds:[createEmbed('✅ Erfolg','Verifizierung erfolgreich!',COLOR_SUCCESS)],ephemeral:true}); } },
  { name:'guildMemberUpdate', async execute(bot,before,after){ if(after.user.bot)return; const full=await bot.db.fetchConfig(after.guild.id); const cfg=full.verify_system||{}; const add=(cfg.add_roles||[]).map(String); if(!add.length)return; const had=before.roles.cache; const has=after.roles.cache; const gained=add.some(id=>!had.has(id)&&has.has(id)); if(gained) await sendVerifyDm(bot, after, 'Dir wurde eine Verify-Rolle gegeben.'); } },
];
module.exports={commands,events};
